# Generated by Django 4.0.3 on 2022-06-02 05:49

from django.db import migrations, models
import rental_property.models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_property', '0016_rentalunit_rent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitalbum',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=rental_property.models.get_house_album_path, width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='unitalbum',
            name='image_height',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='unitalbum',
            name='image_width',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
    ]
